src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: 'to_order')]
class Order
{
    #[ORM\Id]
    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'orders')]
    private User $user;

    #[ORM\Id]
    #[ORM\ManyToOne(targetEntity: Product::class, inversedBy: 'orders')]
    private Product $product;

    #[ORM\Id]
    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Date $Date = null;

    #[ORM\Column(type: 'boolean')]
    private bool $isValidated;

    #[ORM\Column]
    private ?int $quantity = null;

    public function getUser(): User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProduct(): Product
    {
        return $this->product;
    }

    public function setProduct(Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getIsValidated(): bool
    {
        return $this->isValidated;
    }

    public function setIsValidated(bool $isValidated): self
    {
        $this->isValidated = $isValidated;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }
    public function getPrice(): float
    {
        return $this->product->getPrice();
    }



    public function getDate(): ?Date
    {
        return $this->Date;
    }

    public function setDate(?Date $Date): self
    {
        $this->Date = $Date;

        return $this;
    }
}

templates/pages/cart.html.twig
{% extends "base.html.twig" %}

{% block title %}GN Vape - Panier
{% endblock %}

{% block body %}
	{% if orders is defined %}
		<section class="h-100 h-custom">
			<div class="container py-5 h-100">
				<div class="row d-flex justify-content-center align-items-center h-100">
					<div class="col-12">
						<div class="card card-registration card-registration-2" style="border-radius: 15px;">
							<div class="card-body p-0">
								<div class="row g-0">
									<div class="col-lg-8">
										<div class="p-5">
											<div class="d-flex justify-content-between align-items-center mb-5">
												<h1 class="fw-bold mb-0 text-light">Mon Panier</h1>
												<h6 class="mb-0 text-muted">{{ quantityItems }}
													articles</h6>
											</div>
											<hr class="my-4">
											{% for order in orders %}
												{% if not order.isValidated %}
													{% set produit = order.product %}
													{% set nomProduit = produit.name %}
													{% set prixProduit = produit.price %}
													{% set imgProduit = produit.img %}
													{% set typeProduit = produit.type.nametype %}
													{% set quantity = order.quantity %}
													{% set date = order.date %}

													<div class="row mb-4 d-flex justify-content-between align-items-center">
														<div class="col-md-2 col-lg-2 col-xl-2">
															<img src="{{ imgProduit }}" class="img-fluid rounded-3" alt="img du produit">
														</div>
														<div class="col-md-3 col-lg-3 col-xl-3">
															<h6 class="text-muted">{{ typeProduit }}</h6>
															<h6 class="text-light mb-0">{{ nomProduit }}</h6>
														</div>
														<div class="col-md-3 col-lg-3 col-xl-2 d-flex">
															<h6 class="mb-0">{{ quantity }}</h6>
														</div>
														<div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
															<h6 class="mb-0">{{ prixProduit }}
																€</h6>
														</div>

														<a class="btn btn-danger" href={{ path('removeCart.index', { id: produit.id, idDate: date.id })}}>Supprimer</a>


													</div>

												{% endif %}
											{% endfor %}

											<hr class="my-4">

											<div class="pt-5">
												<h6 class="mb-0">
													<a href="/shop" class="btn btn-primary">
														<i class="fas fa-long-arrow-alt-left me-2"></i>Retour au shop
													</a>
												</h6>
											</div>
										</div>
									</div>
									<div class="col-lg-4 bg-grey">
										<div class="p-5">
											<h3 class="fw-bold mb-5 mt-2 pt-1">Résumé</h3>
											<hr class="my-4">

											<div class="d-flex justify-content-between mb-4">
												<h5 class="text-uppercase">Articles :
													{{ quantityItems }}</h5>
											</div>
											<hr class="my-4">

											<div class="d-flex justify-content-between mb-5">
												<h5 class="text-uppercase">Prix total :</h5>
												<h5>{{ total }}
													€</h5>
											</div>
											<a href="/toCommand">
												<button type="button" class="btn btn-secondary btn-block btn-lg" data-mdb-ripple-color="dark">Commander</button>
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	{% endif %}
{% endblock %}

templates/pages/commands.html.twig
{% extends "base.html.twig" %}

{% block title %}GN Vape - Commandes
{% endblock %}

{% block body %}
	{% set groupedOrders = {} %}

	{% for order in orders %}
		{% if order.isValidated %}

			{% set date = order.date %}
			{% if date is not null %}
				{% set orderedAt = date.getDatetime()|date('d-m-Y') %}
				{% if groupedOrders[orderedAt] is not defined %}
					{% set groupedOrders = groupedOrders|merge({(orderedAt): [order]}) %}
				{% else %}
					{% set groupedOrders = groupedOrders|merge({(orderedAt): groupedOrders[orderedAt]|merge([order])}) %}
				{% endif %}
			{% endif %}
		{% endif %}
	{% endfor %}

	{% if groupedOrders is empty %}
		<p>Aucune commande validée n'est disponible.</p>
	{% else %}
		{% for date, ordersByDate in groupedOrders %}
			<div class="card mb-3" style="max-width: 540px;">
				<div class="row no-gutters">
					<div class="col-md-4">
						<img src="img/ecig.jpg" class="card-img" alt="imgProduit">
					</div>
					<div class="col-md-8">
						<div class="card-body">
							<h5 class="card-title">Commande du
								{{ date }}</h5>
							{% for order in ordersByDate %}
								{% set produit = order.product %}
								{% set nomProduit = produit.name %}
								{% set descProduit = produit.description %}
								{% set prixProduit = produit.price %}
								{% set imgProduit = produit.img %}
								{% set typeProduit = produit.type.nametype %}
								{% set quantity = order.quantity %}
								<p class="card-text">{{ nomProduit }}
									x{{ quantity }}</p>
							{% endfor %}
							<p class="card-text">Prix total de la commande :
								{{ total }}
								€</p>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
	{% endif %}
{% endblock %}

templates/pages/home.html.twig
{% extends "base.html.twig" %}

{% block title %}GN Vape - Accueil
{% endblock %}
{% block body %}
	<div class="container mt-4">
	{% for message in app.flashes('success') %}
        <div class="alert alert-success mt-4">
          {{ message }}
        </div>
        {% endfor %}
		<h1 class="display-4">Bienvenue sur GN Vape !</h1>
		<p class="lead">Cette application représente une boutique de vape en ligne.</p>
		<hr class="mt-4">
		<p>Pour commencer, rendez-vous sur le shop pour voir nos produits.</p>
		<p>Ce site a été réalisé dans le cadre de l'épreuve E5 du BTS SIO.</p>
	</div>
	{% apply inline_css %}
	<style>
		.img-fluid {
			width: 400px;
			height: 150px;
		}
	</style>
	<div class="container">
		<div class="row py-3 border-bottom">
			<div class="col-sm-4 col-lg-3 text-center text-sm-start">
				<div class="main-logo">
					<img src="{{ asset('img/logo.png') }}" alt="logo" class="img-fluid">
				</div>
			</div>
		</div>
	</div>
{% endapply %}
{% endblock %}

templates/pages/list_products.html.twig
{% extends "base.html.twig" %}

{% block title %}GN Vape - Shop
{% endblock %}
{% block body %}
	{% include "components/navbar_shop.html.twig" %}
    {% for produit in produits %}
        {% set nomProduit = produit.name %}
        {% set prixProduit = produit.price %}
        {% set imgProduit = produit.img %}

	<section class="py-5">
		<div class="container px-4 px-lg-5 mt-5">
			<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
				<div class="col mb-5">
					<div
						class="card h-100">
						<!-- Product image-->
						<img
						class="card-img-top" src={{ imgProduit }} alt="..."/>
						<!-- Product details-->
						<div class="card-body p-4">
							<div
								class="text-center">
								<!-- Product name-->
								<h5 class="fw-bolder">{{ nomProduit }}</h5>
								<!-- Product price-->
								{{ prixProduit }}€
							</div>
						</div>
						<!-- Product actions-->
						<div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
							<div class="text-center">
								<a class="btn btn-outline-dark mt-auto" href={{ path('product.index', { id: produit.id })}}>En savoir plus</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div></section>
{% endfor %}
{% endblock %}

templates/pages/product.html.twig
{% extends "base.html.twig" %}

{% block title %}GN Vape - Shop
{% endblock %}
{% block body %}
	<section class="py-5">
		<div class="container px-4 px-lg-5 my-5">
			<div class="row gx-4 gx-lg-5 align-items-center">
				<div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ asset(produit.img) }}" alt="..."/></div>
				<div class="col-md-6">
					<div class="small mb-1">GNV - Produit numero
						{{ produit.id }}</div>
					<h1 class="display-5 fw-bolder">{{ produit.name }}</h1>
					<div class="fs-5 mb-5">
						<span>{{ produit.price }}€</span>
					</div>
					<p class="lead">{{ produit.description }}</p>
					<div class="d-flex">
						<a href={{ path('ajoutPanier.index', { id: produit.id })}} class="btn btn-secondary btn-lg text-uppercase fs-6 rounded-1">Ajouter au panier</a>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/pages/profile.html.twig
{% extends "base.html.twig" %}

{% block title %}GN Vape - Profil{% endblock %}

{% block body %}
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-6 mb-4 mb-lg-0">
        <div class="card mb-3" style="border-radius: .5rem;">
          <div class="row g-0">
            <div class="col-md-4 gradient-custom text-center text-white"
              style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
              <img src="https://st3.depositphotos.com/1672707/13758/v/600/depositphotos_137581214-stock-illustration-no-vaping-restriction-icon.jpg"
                alt="Avatar" class="img-fluid my-5" style="width: 80px;" />
              {% for user in User %}
              <h5>{{ user.firstName }} {{ user.lastName }}</h5>
            </div>
            <div class="col-md-8">
              <div class="card-body p-4">
                <h6>Informations</h6>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h6>Email</h6>
                    <p class="text-muted">{{ user.email }}</p>
                  </div>
                  <div class="col-6 mb-3">
                    <h6>Téléphone</h6>
                    <p class="text-muted">{{ user.phoneNumber }}</p>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/pages/shop.html.twig
{% extends "base.html.twig" %}

{% block title %}GN Vape - Shop
{% endblock %}
{% block body %}
	{% include "components/navbar_shop.html.twig" %}

	{% apply inline_css %}
	<style>
		.img-thumbnail {
			max-width: 150px;
			max-height: 150px;
		}
	</style>
	{% for message in app.flashes('success') %}
		<div class="alert alert-dismissible alert-success">
  			<button type="button" class="btn-close" data-bs-dismiss="alert"></button>
			{{ message }}
		</div>
	{% endfor %}
	<section class="py-3" style="background-image: url('images/background-pattern.jpg');background-repeat: no-repeat;background-size: cover;">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">

					<div class="banner-blocks">

						<div class="banner-ad large block-1">

							<div class="swiper main-swiper">
								<div class="swiper-wrapper">

									<div class="swiper-slide">
										<div class="row banner-content p-5">
											<div class="content-wrapper col-md-7">
												<div class="categories mb-3 pb-3">100% vape</div>
												<h3 class="banner-title">Nouvelle Vaporesso deluxe</h3>
												<p>La Deluxe n'est pas seulement la plus belle mais aussi la plus féroce bête de vapotage que vous ayez jamais vue. Son écran de 2 pouces est à couper le souffle, intégré dans un écran élégant avec des boutons tactiles réactifs, vous permettant de bénéficier de la meilleure expérience possible avec cet appareil de haute technologie.</p>
												<a href={{ path('product.index', { id: 2 } )}} class="btn btn-outline-dark btn-lg text-uppercase fs-6 rounded-1">En savoir plus</a>
											</div>
											<div class="img-wrapper col-md-5">
												<img src="img/vapo_deluxe.png" class="img-thumbnail">
											</div>
										</div>
									</div>

									<div class="swiper-slide">
										<div class="row banner-content p-5">
											<div class="content-wrapper col-md-7">
												<div class="categories mb-3 pb-3">100% fresh</div>
												<h3 class="banner-title">Nouveau goût menthe fraiche par Alfaliquid</h3>
												<p>L'e-liquide Menthe Fraiche Alfaliquid Original assure une saveur ultra fraîche avec une bonne tenue en bouche. Disponible en 10mL, PG/VG 76/24, 6 taux de nicotine. Un liquide à vapoter de préférence sur des résistances supérieurs à 1 ohm avec une puissance faible.</p>
												<a href={{ path('product.index', { id: 5 } )}} class="btn btn-outline-dark btn-lg text-uppercase fs-6 rounded-1">En savoir plus</a>
											</div>
											<div class="img-wrapper col-md-5">
												<img src="img/alfamenthe.webp" class="img-thumbnail">
											</div>
										</div>
									</div>

									<div class="swiper-slide">
										<div class="row banner-content p-5">
											<div class="content-wrapper col-md-7">
												<div class="categories mb-3 pb-3">100% power</div>
												<h3 class="banner-title">Nouvelle resistance 0.5 ohm par Eleaf</h3>
												<p>Résistances Eleaf. Pack 6 résistances EC Eleaf. Pack de 6 résistances EC Eleaf pour les clearomiseur Melo, Melo 2, Melo 3 et IJust 2. Les résistances EC sont fabriquées avec du coton 100% organique et du fil résistif de très haute qualité pour un excellent rendu des saveurs. Vendues par lot de 6. Produit certifié Eleaf.</p>
												<a href={{ path('product.index', { id: 3 } )}} class="btn btn-outline-dark btn-lg text-uppercase fs-6 rounded-1">En savoir plus</a>
											</div>
											<div class="img-wrapper col-md-5">
												<img src="img/resistance.webp" class="img-thumbnail">
											</div>
										</div>
									</div>
								</div>

								<div class="swiper-pagination"></div>

							</div>
						</div>
					</div>
					<!-- / Banner Blocks -->

				</div>
			</div>
		</div>
	</section>
	{% endapply %}
{% endblock %}